In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

In [3]:

df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [4]:

df.isnull().mean() * 100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [5]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [7]:

X_train.head()

      Age  Pclass     Fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000
182   9.0       3  31.3875
876  20.0       3   9.8458

In [32]:
knn = KNNImputer(n_neighbors=1,weights='distance')

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [33]:
lr = LogisticRegression()

lr.fit(X_train_trf,y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.7206703910614525

In [37]:
dic={}
for i in range(1,21):
    knn = KNNImputer(n_neighbors=i,weights='distance')
    X_train_trf = knn.fit_transform(X_train)
    X_test_trf = knn.transform(X_test)
    lr = LogisticRegression()
    lr.fit(X_train_trf,y_train)
    y_pred = lr.predict(X_test_trf)
    dic[f'no. of neighours: {i}']=accuracy_score(y_test,y_pred)

dic

{'no. of neighours: 1': 0.7206703910614525,
 'no. of neighours: 2': 0.7094972067039106,
 'no. of neighours: 3': 0.7039106145251397,
 'no. of neighours: 4': 0.7039106145251397,
 'no. of neighours: 5': 0.7039106145251397,
 'no. of neighours: 6': 0.7039106145251397,
 'no. of neighours: 7': 0.7039106145251397,
 'no. of neighours: 8': 0.7039106145251397,
 'no. of neighours: 9': 0.7039106145251397,
 'no. of neighours: 10': 0.7039106145251397,
 'no. of neighours: 11': 0.7039106145251397,
 'no. of neighours: 12': 0.7039106145251397,
 'no. of neighours: 13': 0.7039106145251397,
 'no. of neighours: 14': 0.7039106145251397,
 'no. of neighours: 15': 0.7039106145251397,
 'no. of neighours: 16': 0.7039106145251397,
 'no. of neighours: 17': 0.7039106145251397,
 'no. of neighours: 18': 0.7039106145251397,
 'no. of neighours: 19': 0.7039106145251397,
 'no. of neighours: 20': 0.7039106145251397}

In [22]:
# Comparision with Simple Imputer --> mean

si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [23]:
lr = LogisticRegression()

lr.fit(X_train_trf2,y_train)

y_pred2 = lr.predict(X_test_trf2)

accuracy_score(y_test,y_pred2)

0.6927374301675978