In [129]:
import pandas as pd
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier

In [4]:
iris=datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [5]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)

In [7]:
df['flower'] = iris.target

In [10]:
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x] )

In [14]:
df['flower'].value_counts()

flower
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [41]:
from sklearn.model_selection import train_test_split

X=df.drop(columns=['flower'])
y=df['flower']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [37]:
X_train.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
42                 4.4               3.2                1.3               0.2
45                 4.8               3.0                1.4               0.3
115                6.4               3.2                5.3               2.3
103                6.3               2.9                5.6               1.8
11                 4.8               3.4                1.6               0.2

In [18]:
from sklearn.svm import SVC

In [42]:
model = SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9555555555555556

In [47]:
from sklearn.model_selection import cross_val_score
import numpy as np

In [50]:
np.mean(cross_val_score(SVC(kernel='linear',C=10,gamma='auto'),X,y,cv=5))

np.float64(0.9733333333333334)

In [49]:
np.mean(cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),X,y,cv=5))

np.float64(0.9666666666666668)

In [48]:
np.mean(cross_val_score(SVC(kernel='rbf',C=10,gamma='auto'),X,y,cv=5))

np.float64(0.9800000000000001)

In [56]:
kernels = ['rbf','linear']
C=[1,10,20,4,5,14,20,89,70,32,65]
avg_score = {}

for Kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(SVC(kernel=Kval,C=cval,gamma='auto'),X,y,cv=10)
        avg_score[Kval + ' - '+ str(cval)]=np.mean(cv_scores)

avg_score

{'rbf - 1': np.float64(0.9800000000000001),
 'rbf - 10': np.float64(0.9733333333333334),
 'rbf - 20': np.float64(0.9666666666666668),
 'rbf - 4': np.float64(0.9733333333333334),
 'rbf - 5': np.float64(0.9733333333333334),
 'rbf - 14': np.float64(0.9666666666666668),
 'rbf - 89': np.float64(0.9600000000000002),
 'rbf - 70': np.float64(0.9600000000000002),
 'rbf - 32': np.float64(0.9600000000000002),
 'rbf - 65': np.float64(0.9600000000000002),
 'linear - 1': np.float64(0.9733333333333334),
 'linear - 10': np.float64(0.9800000000000001),
 'linear - 20': np.float64(0.9666666666666668),
 'linear - 4': np.float64(0.9733333333333334),
 'linear - 5': np.float64(0.9733333333333334),
 'linear - 14': np.float64(0.9733333333333334),
 'linear - 89': np.float64(0.9733333333333334),
 'linear - 70': np.float64(0.9800000000000001),
 'linear - 32': np.float64(0.9666666666666668),
 'linear - 65': np.float64(0.9733333333333334)}

In [57]:
from sklearn.model_selection import GridSearchCV

In [105]:
clf = GridSearchCV(SVC(gamma='auto'),{
    'C':[x for x in range(1,51)],
    'kernel':['rbf','linear']
},cv=10,return_train_score=False)

clf.fit(X,y)
# clf.cv_results_

GridSearchCV(cv=10, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
                               15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
                               27, 28, 29, 30, ...],
                         'kernel': ['rbf', 'linear']})

In [109]:
p=pd.DataFrame(clf.cv_results_)

In [110]:
p.head(1)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,split5_test_score,split6_test_score,split7_test_score,split8_test_score,split9_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009581,0.009819,0.004595,0.00134,1,rbf,"{'C': 1, 'kernel': 'rbf'}",1.0,0.933333,1.0,1.0,1.0,0.933333,0.933333,1.0,1.0,1.0,0.98,0.030551,1

In [98]:
keyValue={}

for i in p['params'].values:
    print( str(i) + str(p[p['params']==i]['mean_test_score']))

{'C': 1, 'kernel': 'rbf'}0    0.98
Name: mean_test_score, dtype: float64
{'C': 1, 'kernel': 'linear'}1    0.973333
Name: mean_test_score, dtype: float64
{'C': 10, 'kernel': 'rbf'}2    0.973333
Name: mean_test_score, dtype: float64
{'C': 10, 'kernel': 'linear'}3    0.98
Name: mean_test_score, dtype: float64
{'C': 12, 'kernel': 'rbf'}4    0.973333
Name: mean_test_score, dtype: float64
{'C': 12, 'kernel': 'linear'}5    0.98
Name: mean_test_score, dtype: float64
{'C': 124, 'kernel': 'rbf'}6    0.966667
Name: mean_test_score, dtype: float64
{'C': 124, 'kernel': 'linear'}7    0.973333
Name: mean_test_score, dtype: float64
{'C': 20, 'kernel': 'rbf'}8    0.966667
Name: mean_test_score, dtype: float64
{'C': 20, 'kernel': 'linear'}9    0.966667
Name: mean_test_score, dtype: float64
{'C': 50, 'kernel': 'rbf'}10    0.96
Name: mean_test_score, dtype: float64
{'C': 50, 'kernel': 'linear'}11    0.973333
Name: mean_test_score, dtype: float64
{'C': 13, 'kernel': 'rbf'}12    0.973333
Name: mean_test_score, dtype: float64
{'C': 13, 'kernel': 'linear'}13    0.973333
Name: mean_test_score, dtype: float64

In [111]:
p[['params','mean_test_score']]

                           params  mean_test_score
0       {'C': 1, 'kernel': 'rbf'}         0.980000
1    {'C': 1, 'kernel': 'linear'}         0.973333
2       {'C': 2, 'kernel': 'rbf'}         0.980000
3    {'C': 2, 'kernel': 'linear'}         0.980000
4       {'C': 3, 'kernel': 'rbf'}         0.973333
..                            ...              ...
95  {'C': 48, 'kernel': 'linear'}         0.973333
96     {'C': 49, 'kernel': 'rbf'}         0.960000
97  {'C': 49, 'kernel': 'linear'}         0.973333
98     {'C': 50, 'kernel': 'rbf'}         0.960000
99  {'C': 50, 'kernel': 'linear'}         0.973333

[100 rows x 2 columns]

In [106]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [107]:
clf.best_score_

np.float64(0.9800000000000001)

In [ ]:
# The problem with the gridSearch Cv is resource cost now our dataset is small but it is large it checks for each value of paramtere so tackle this we have the randomized grid search cv

In [114]:
from sklearn.model_selection import RandomizedSearchCV

In [125]:
rs = RandomizedSearchCV(SVC(gamma='auto'),{
    'C':[x for x in range(1,50)],
    'kernel':['rbf','linear']
},n_iter=5,cv=5)

rs.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=5,
                   param_distributions={'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
                                              12, 13, 14, 15, 16, 17, 18, 19,
                                              20, 21, 22, 23, 24, 25, 26, 27,
                                              28, 29, 30, ...],
                                        'kernel': ['rbf', 'linear']})

In [126]:
pd.DataFrame(rs.cv_results_)[['params','mean_test_score']]

                          params  mean_test_score
0     {'kernel': 'rbf', 'C': 21}         0.966667
1     {'kernel': 'rbf', 'C': 36}         0.966667
2      {'kernel': 'rbf', 'C': 3}         0.973333
3      {'kernel': 'rbf', 'C': 5}         0.980000
4  {'kernel': 'linear', 'C': 47}         0.966667

In [127]:
rs.best_params_

{'kernel': 'rbf', 'C': 5}

In [128]:
rs.best_score_

np.float64(0.9800000000000001)

In [141]:
models = {
    'SVM':{
        'model':SVC(gamma='auto'),
        'params':{
            'C':[1,15,10,20],
            'kernel':['rbf','linear']
        }
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,40,10,20]
        }
    }
}

In [142]:
scores=[]

for model_name,mp in models.items():
    clf=GridSearchCV(mp['model'],mp['params'],cv=10)
    clf.fit(X,y)
    scores.append({
        'model':model_name,
        'best_params':clf.best_params_,
        'best_score':clf.best_score_
    })

In [143]:
pd.DataFrame(scores)

           model                best_params  best_score
0            SVM  {'C': 1, 'kernel': 'rbf'}    0.980000
1  random_forest       {'n_estimators': 40}    0.966667